### ISSUE TITLE
Changes to the labeler config will not work in the PR that they are submitted with

### ISSUE THREAD

**Issue by TheCleric** [ffittschen/pr-branch-labeler#7]
I ran into an issue where the labeler wasn't working for me. After adding some debugging to a fork of it, I discovered since getContents of the config file operates off the repo's default version of the config, changes to the config within the PR are ignored.

**Comment by TheCleric** [comment]
I have created a PR to address this. It accesses the config file in the current head ref of the PR:

https://github.com/ffittschen/pr-branch-labeler/pull/6

**Comment by ffittschen** [comment]
Hi, yes we came to the same conclusion in the last issue: #4. Thanks for taking the time to open a PR for it!
